Repository boostcamp-2020/IssueTracker-31, pull requests merged in 2020-11, with the labels that each got.

#47 Close #28 Feature/api/get-label
  backend/src/controller/index.js
  backend/src/controller/label/index.js
  backend/src/controller/label/label.js
  backend/src/model/label.js
  backend/src/service/label.js
  backend/src/util/resMessage.js
  backend/src/util/statusCode.js
Labels: review needed

#48 Close #30 Feature/api/get-milestone
  backend/src/controller/index.js
  backend/src/controller/milestone/index.js
  backend/src/controller/milestone/milestone.js
  backend/src/model/milestone.js
  backend/src/service/milestone.js
Labels: review needed

#46 Close #9 feature/backend/get-issue-list-api
  backend/src/app.js
  backend/src/controller/index.js
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/issue.js
  backend/src/model/query/issue.js
  backend/src/service/issue.js
  backend/src/util/error-response.js
Labels: review needed

#51 Feature/issue list/get issue list api (#6)
  frontend/.babelrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/issue.js
  frontend/src/util/request.js
  frontend/webpack.config.js
Labels: review needed

#52 Close #36 Feature/issue component
  backend/.eslintrc.json
  frontend/.babelrc
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/component/IssueListPage/Issue.js
  frontend/src/component/common/Label.js
  frontend/src/util/util.js
Labels: review needed

#53 Close #18 feature/oauth/github-login
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controller/user/index.js
  backend/src/controller/user/user.js
  frontend/src/page/Login.js
Labels: review needed

#49 Feature/popup component (#17)
  frontend/src/component/common/PopUp.js
Labels: changes requested

#120 Feature/filter-UI (#14, #34)
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/src/component/IssueListPage/FilterSelector.js
  frontend/src/component/IssueListPage/FilterSelector.test.js
  frontend/src/component/IssueListPage/IssueFilter.js
  frontend/src/page/IssueList.js
Labels: review needed

#136 Feature/milestone page (#72, #75)
  frontend/public/js/CloseIcon.js
  frontend/public/js/DateIcon.js
  frontend/public/js/LabelIcon.js
  frontend/public/js/OpenIcon.js
  frontend/src/component/MilestonePage/Milestone.js
  frontend/src/component/MilestonePage/MilestoneList.js
  frontend/src/index.js
  frontend/src/page/Milestone.js
Labels: review needed

#124 Feat: add search bar component (#37, #39, #40)
  frontend/src/component/IssueListPage/SearchBar.js
  frontend/src/page/IssueList.js
Labels: review needed

#133 Feature/GitHub action (#121)
  .github/workflows/deploy.yml
  backend/.eslintrc.json
  backend/.prettierrc.json
  backend/package.json
  backend/src/app.js
  backend/src/controller/index.js
  backend/src/service/user.js
  frontend/package.json
  frontend/src/util/request.js
Labels: review needed

#131 Feature/label page (#71)
  frontend/.eslintrc.json
  frontend/.prettierrc.json
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/LabelPage/LabelList.js
  frontend/src/component/LabelPage/NewLabelButton.js
  frontend/src/component/LabelPage/TabButton.js
  frontend/src/index.js
  frontend/src/page/Label/Label.js
  frontend/src/page/Label/Label.test.js
Labels: review needed

#129 Feature/db setting (#127, #128)
  backend/src/controller/milestone/index.js
  backend/src/controller/milestone/milestone.js
  backend/src/model/init.sql
  backend/src/model/label.js
  backend/src/model/milestone.js
  backend/src/service/label.js
  backend/src/service/milestone.js
Labels: review needed

#134 Feature/label page buttons (#72, #73)
  frontend/src/component/LabelPage/NewLabelButton.js
  frontend/src/component/LabelPage/TabButton.js
  frontend/src/component/common/Button.js
  frontend/src/component/common/TabButton.js
  frontend/src/page/Label/Label.js
Labels: review needed

#138 Feature/issue list component (#31 #33 #29 #35)
  backend/src/model/query/issue.js
  backend/src/service/issue.js
  frontend/src/api/issue.js
  frontend/src/component/IssueListPage/FilterSelector.js
  frontend/src/component/IssueListPage/Issue.js
  frontend/src/component/IssueListPage/IssueFilter.js
  frontend/src/component/IssueListPage/IssueList.js
  frontend/src/component/common/PopUp.js
  frontend/src/page/IssueList.js
  frontend/src/util/hook.js
Labels: review needed

#130 Feature/common/link-button (#1, #2, #7, #8)
  frontend/public/js/LabelIcon.js
  frontend/public/js/OpenIcon.js
  frontend/src/component/IssueListPage/LinkButton.js
  frontend/src/component/common/Button.js
  frontend/src/component/common/EventButton.js
  frontend/src/component/common/LinkButton.js
  frontend/src/component/common/TabButton.js
  frontend/src/page/IssueList.js
  frontend/src/page/Label/Label.js
Labels: review needed

#132 Feature/page routing (#3, #4, #5)
  frontend/src/index.js
  frontend/src/page/NewIssue.js
Labels: changes requested, review needed

#141 Feat: add /api to API path (#140)
  backend/src/app.js
  frontend/src/util/request.js
Labels: review needed

#142 Refactor/popup (#139, #22)
  backend/src/model/init.sql
  frontend/public/images/defaultUserIcon.png
  frontend/src/api/user.js
  frontend/src/component/IssueListPage/FilterSelector.js
  frontend/src/component/IssueListPage/IssueFilter.js
  frontend/src/component/IssueListPage/SearchBar.js
  frontend/src/component/common/PopUp.js
  frontend/src/page/IssueList.js
Labels: review needed

#125 Feature/auth/token (#16, #19, #20)
  backend/package-lock.json
  backend/src/app.js
  backend/src/controller/index.js
  backend/src/controller/user/index.js
  backend/src/controller/user/user.js
  backend/src/model/query/user.js
  backend/src/model/user.js
  backend/src/service/user.js
  frontend/src/index.js
  frontend/src/page/IssueList.js
Labels: review needed

#143 Feature/issue list component (#27)
  frontend/src/api/issue.js
  frontend/src/component/IssueListPage/FilterSelector.js
  frontend/src/component/IssueListPage/Issue.js
  frontend/src/component/IssueListPage/IssueFilter.js
  frontend/src/component/IssueListPage/IssueList.js
  frontend/src/component/IssueListPage/SearchBar.js
  frontend/src/component/common/PopUp.js
Labels: review needed

#144 Feature/api/create issue (#76)
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/comment.js
  backend/src/model/commentImageUrl.js
  backend/src/model/issue.js
  backend/src/model/query/comment.js
  backend/src/model/query/commnetImageUrl.js
  backend/src/model/query/issue.js
  backend/src/service/issue.js
  backend/src/util/relation-maker.js
Labels: review needed

#151 Refactor/milestone
  frontend/jest.setup.js
  frontend/src/component/MilestonePage/MilestoneList.js
  frontend/src/component/common/Button.js
  frontend/src/component/common/TabButton.js
  frontend/src/index.js
  frontend/src/page/Milestone/Milestone.js
  frontend/src/page/Milestone/Milestone.test.js
Labels: review needed

#152 Feature/oauth/github-fix
  backend/src/controller/user/user.js
  frontend/src/page/Login.js
Labels: review needed

#153 Feature/request/milestone detail (#135)
  frontend/src/api/milestone.js
  frontend/src/page/Milestone/Milestone.js
Labels: review needed

#157 Feature/component/milestone (#77)
  frontend/src/component/MilestonePage/Milestone.js
  frontend/src/util/util.js
Labels: review needed

#160 Feature/request/milestone-delete (#78)
  frontend/src/api/milestone.js
  frontend/src/component/MilestonePage/Milestone.js
  frontend/src/component/MilestonePage/MilestoneList.js
Labels: review needed

#162 Feature/api/delete label (#100)
  backend/src/controller/label/index.js
  backend/src/controller/label/label.js
  backend/src/model/label.js
  backend/src/model/query/label.js
  backend/src/service/label.js
Labels: review needed

#159 Feature/api/create label (#102)
  backend/src/controller/issue/issue.js
  backend/src/controller/label/index.js
  backend/src/controller/label/label.js
  backend/src/model/init.sql
  backend/src/model/label.js
  backend/src/model/query/label.js
  backend/src/service/label.js
  backend/src/util/error-response.js
  backend/src/util/statusCode.js
Labels: review needed

#156 Feature/api/milestone detail (#87)
  backend/src/controller/milestone/index.js
  backend/src/controller/milestone/milestone.js
  backend/src/model/milestone.js
  backend/src/model/query/milestone.js
  backend/src/service/milestone.js
Labels: review needed

#166 Refactor/db/delete-CommentImageUrl (#147, #61)
  backend/src/model/init.sql
Labels: review needed

#164 Feature/page/create issue
  frontend/src/component/common/ProfileWithContent.js
  frontend/src/component/common/Sidebar.js
  frontend/src/component/common/SpeechBubble.js
  frontend/src/index.js
  frontend/src/page/CreateIssue.js
  frontend/src/page/NewIssue.js
Labels: review needed

#155 Feature/issues/update-open-close (#21)
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/issue.js
  backend/src/model/query/issue.js
  backend/src/service/issue.js
Labels: review needed

#163 Feature/api/update label (#101)
  backend/src/controller/label/index.js
  backend/src/controller/label/label.js
  backend/src/model/label.js
  backend/src/model/query/label.js
  backend/src/service/label.js
Labels: review needed

#167 Feat: add create issue request (#56)
  frontend/src/api/issue.js
Labels: review needed

#171 Feature/api/get issue detail (#92)
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/issue.js
  backend/src/model/label.js
  backend/src/model/milestone.js
  backend/src/model/query/issue.js
  backend/src/model/query/label.js
  backend/src/model/query/milestone.js
  backend/src/model/query/user.js
  backend/src/model/user.js
  backend/src/service/issue.js
Labels: review needed

#172 Feature/api/milestone (#83, #88, #89, #90)
  backend/src/app.js
  backend/src/controller/milestone/index.js
  backend/src/controller/milestone/milestone.js
  backend/src/model/index.js
  backend/src/model/milestone.js
  backend/src/model/query/milestone.js
  backend/src/service/milestone.js
  backend/src/util/utility.js
Labels: review needed

#170 Feature/api/update comments (#67)
  backend/src/controller/comment/comment.js
  backend/src/controller/comment/index.js
  backend/src/controller/index.js
  backend/src/controller/user/user.js
  backend/src/model/comment.js
  backend/src/model/query/comment.js
  backend/src/service/comment.js
Labels: review needed

#177 Feature/fix/client side routing (#176)
  backend/src/app.js
  frontend/webpack.config.js
Labels: review needed

#173 Feautre/api/issue zero value filter(#149)
  backend/src/model/query/issue.js
  backend/src/service/issue.js
Labels: review needed

#178 Feature/api/issue assignee update (#96)
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/init.sql
  backend/src/model/query/user.js
  backend/src/model/user.js
  backend/src/service/issue.js
Labels: review needed

#174 Feature/api/get issue comments (#65)
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/comment.js
  backend/src/model/query/comment.js
  backend/src/service/issue.js
Labels: review needed

#180 Feature/issue detail header (#62, #63)
  frontend/public/js/ClosedIssueIcon.js
  frontend/public/js/OpenIssueIcon.js
  frontend/src/api/issue.js
  frontend/src/component/IssueDetailPage/IssueDetailHeader.js
  frontend/src/component/common/Button.js
  frontend/src/component/common/EventButton.js
  frontend/src/component/common/ImageInput.js
  frontend/src/component/common/LinkButton.js
  frontend/src/index.js
  frontend/src/page/IssueDetail.js
Labels: review needed

#179 Feature/api/issue label update (#175)
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/label.js
  backend/src/model/query/label.js
  backend/src/service/issue.js
Labels: review needed

#183 Feature/image upload (#58, #59)
  frontend/src/api/comment.js
  frontend/src/component/common/ImageInput.js
Labels: review needed

#185 Feature/api/fix error get issue ( #184)
  backend/src/model/query/issue.js
  backend/src/model/query/milestone.js
Labels: review needed

#186 Fix: fixed uncommited button error
  backend/src/app.js
  frontend/src/component/common/LinkButton.js
Labels: review needed

#181 Feature/api/issue update (#94)
  backend/src/controller/issue/index.js
  backend/src/controller/issue/issue.js
  backend/src/model/issue.js
  backend/src/model/query/issue.js
  backend/src/service/issue.js
Labels: review needed

#188 Refactor: add constant of BE
  backend/src/app.js
  backend/src/util/resMessage.js
  backend/src/util/statusCode.js
  frontend/webpack.config.js
Labels: review needed

#191 Refactor/page/milestone (#154)
  frontend/src/component/MilestonePage/Milestone.js
  frontend/src/component/MilestonePage/MilestoneList.js
  frontend/src/page/Milestone/Milestone.js
  frontend/src/util/util.js
Labels: review needed

#190 Fix/redirect error (#168)
  backend/src/app.js
  backend/src/controller/user/user.js
  frontend/src/util/request.js
Labels: review needed

#193 Feature/create issue page
  backend/src/controller/issue/issue.js
  backend/src/service/issue.js
  frontend/src/api/issue.js
  frontend/src/component/common/Button.js
  frontend/src/component/common/EventButton.js
  frontend/src/component/common/content/ProfileWithContent.js
  frontend/src/component/common/content/WritingArea.js
  frontend/src/index.js
  frontend/src/page/CreateIssue.js
Labels: review needed

#192 Feature/label components (#113)
  frontend/src/api/label.js
  frontend/src/component/LabelPage/Label.js
  frontend/src/component/LabelPage/LabelForm/LabelForm.js
  frontend/src/component/LabelPage/LabelList.js
  frontend/src/page/Label/Label.js
  frontend/src/page/Milestone/Milestone.js
Labels: review needed

#195 Feature/issue create/sidebar component (#64, 70, 80, 82, 84)
  frontend/public/js/SettingIcon.js
  frontend/src/api/milestone.js
  frontend/src/component/common/Button.js
  frontend/src/component/common/Sidebar.js
  frontend/src/component/common/SidebarItem.js
  frontend/src/page/CreateIssue.js
Labels: review needed

#198 Feat: add request for milestone update (#104)
  frontend/src/api/milestone.js
Labels: review needed

#197 Fix: redirect bug
  backend/src/app.js
  backend/src/controller/user/index.js
  backend/src/controller/user/user.js
  frontend/src/component/IssueListPage/SearchBar.js
  frontend/src/page/IssueList.js
  frontend/src/util/request.js
  frontend/src/util/util.js
Labels: bug, review needed

#204 Feature/comment create (#112)
  backend/src/controller/comment/comment.js
  backend/src/controller/comment/index.js
  backend/src/service/comment.js
Labels: review needed

#205 Feature/image upload (#108)
  .gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/controller/comment/comment.js
  backend/src/controller/comment/index.js
  frontend/src/api/comment.js
  frontend/src/component/common/ImageInput.js
Labels: review needed

#206 Fix/redirect bug
  backend/src/app.js
  frontend/webpack.config.js
Labels: bug, review needed

#208 Feautre/refactoring/issue/detail page (#85)
  backend/src/service/issue.js
  frontend/src/api/issue.js
  frontend/src/component/IssueDetailPage/IssueDetailHeader.js
  frontend/src/component/common/Sidebar.js
  frontend/src/component/common/SidebarItem.js
  frontend/src/page/IssueDetail.js
Labels: review needed

#209 Feat: add milestone new & edit (#116, #117)
  frontend/src/api/milestone.js
  frontend/src/component/MilestonePage/Milestone.js
  frontend/src/component/MilestonePage/MilestoneForm.js
  frontend/src/index.js
  frontend/src/page/EditMilestonePage.js
Labels: review needed

#210 Feature/issue detatil component
  backend/src/controller/comment/comment.js
  backend/src/model/issue.js
  backend/src/model/query/issue.js
  backend/src/service/issue.js
  frontend/src/api/comment.js
  frontend/src/api/issue.js
  frontend/src/component/IssueDetailPage/Comment.js
  frontend/src/component/IssueDetailPage/IssueDetailHeader.js
  frontend/src/component/IssueListPage/FilterSelector.js
  frontend/src/component/common/content/ProfileWithContent.js
  frontend/src/component/common/content/WritingArea.js
  frontend/src/page/CreateIssue.js
  frontend/src/page/IssueDetail.js
Labels: review needed

#212 Feat: add label delete popup (#199)
  frontend/src/component/LabelPage/LabelList.js
Labels: review needed

#216 Feature/issue detatil component (#148 #111 #109 #60)
  backend/package-lock.json
  backend/package.json
  backend/src/controller/comment/comment.js
  backend/src/controller/comment/index.js
  frontend/src/component/IssueDetailPage/Comment.js
Labels: review needed

#221 Feature/issue counting (#222)
  backend/src/model/query/issue.js
  frontend/src/component/IssueListPage/IssueList.js
  frontend/src/component/IssueListPage/SearchBar.js
Labels: bug, review needed

#220 Refactor/label page (#211)
  frontend/src/component/LabelPage/Label.js
  frontend/src/component/LabelPage/LabelForm/LabelForm.js
  frontend/src/component/LabelPage/LabelList.js
  frontend/src/component/common/Button.js
  frontend/src/component/common/Label.js
  frontend/src/page/Label/Label.js
Labels: review needed
